apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cad-checks-
  namespace: configuration-anomaly-detection
spec:
  pipelineRef:
    name: cad-checks-pipeline
  params:
    - name: payload
      value: '{"event": {"data":{"id": "incidentid"}}}'
