apiVersion: v1
kind: ServiceAccount
metadata:
  name: cad-sa
  namespace: configuration-anomaly-detection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cad-eventlistener-role
  namespace: configuration-anomaly-detection
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - create
    verbs:
      - pipelineruns
---
# tekton/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cad-eventlistener-rolebinding
  namespace: configuration-anomaly-detection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cad-eventlistener-role
subjects:
  - kind: ServiceAccount
    name: cad-sa
    namespace: configuration-anomaly-detection
