apiVersion: v1
kind: ServiceAccount
metadata:
  name: cad-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cad-pipelinerun-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
---
# tekton/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cad-pipelinerun-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cad-pipelinerun-role
subjects:
  - kind: ServiceAccount
    name: cad-sa
