---
apiVersion: v1
kind: Secret
metadata:
  name: cad-pd-token
  namespace: configuration-anomaly-detection
type: Opaque
stringData:
  CAD_ESCALATION_POLICY: CHANGEME
  CAD_PD_EMAIL: CHANGEME
  CAD_PD_PW: CHANGEME
  CAD_PD_TOKEN: CHANGEME
  CAD_PD_USERNAME: CHANGEME
  CAD_SILENT_POLICY: CHANGEME
  X_SECRET_TOKEN: CHANGEME
  PD_SIGNATURE: CHANGEME # currently unused